# S. Tweedt
# 7 May 2020
# LULU curation of ASV feature tables


# LULU (Frøslev et al. 2017) is an algorithm for determining likely erroneous ASVs
# (e.g. from PCR or sequencing errors) using co-occurrence and read counts.
# The idea is that sequencing errors are highly similar to real (source) sequences,
# and since they are generated from the source sequences, they occur in the same 
# sample (library). 
# Briefly, LULU flags ASVs as likely errors if they co-occur with a highly similar 
# parent sequence present in greater read abundance, removes these errors from the 
# feature table, and assigns their reads to the parent sequence.


# The LULU function requires:
#   1. An ASV feature table or OTU table generated by your metabarcoding workflow
#     in .tsv/.csv format (e.g. table-dada2.tsv). 
#   2. A "matchlist" generated by comparing the sequences from your metabarcoding 
#     workflow (e.g. rep-seqs.fasta) against themselves. Every sequence thus gets a 
#     list of every other sequence within the dataset that matches it at your desired
#     similarity cutoff (e.g. 85%).

# The matchlist should be a .txt file, and can be generated by running command-line 
# blast - see example script "matchlist_generation.txt".
#   The matchlist must have three columns:
#   1. The focal ASV/OTU identifier
#   2. An ASV/OTU identifier of a similar sequence
#   3. The % measure of similarity between the two


### DETAILED LULU OPERATION DESCRIPTION ###

# Given your feature table and matchlist as input, LULU begins by sorting the ASVs/OTUs 
# first by descreasing occurrence *across* libaries (e.g. ASVs/OTUs that show up in the 
# most libraries are now at the top), then by decreasing total read count. LULU curates 
# data top-down, so sorting the data this way means it will encounter "valid" or "parent"
# sequences before encountering likely errors.

# Starting at the top of the list and working down, LULU evaluates each ASV/OTU:
#   - LULU designates the selected (focal) ASV/OTU as a potential "error".
#   - LULU compares this potential "error" to similar ASVs/OTUs from its match-list.
#   - The similar sequences in the match-list are designated as potential "parents".
#   - Each potential "error" thus may be compared to multiple potential "parents".

# The argument "minimum_match" provides a minimum threshold of sequence similarity to
# consider an ASV/OTU to be an error of another. The default is < minimum_match = 84 >
# (84% similarity).
# Key considerations:
#   - If your matchlist itself was generated with a similarity threhold lower than 84%, 
#     (e.g. blastn -perc_identity 70), then minimum_match will thin the matchlist.
#   - If your matchlist was generated with the same or a more stringent similarity %,
#     (e.g. blastn -perc_identity 85), then minimum_match will use every match in the
#     match-list.
#   - Using a more stringent (e.g. 95%) similarity means pseudogenes or sequencing 
#     error >5% divergent will be left in your data as "valid" ASVs.
#   - Using a less stringent (e.g. 85%) similarity means pseudogenes or sequencing
#     error <=15% divergent will be called errors and merged with parent sequences.
#     HOWEVER, sequences within 15% divergence will also likely include true haplotypes 
#     and intraspecific variation, which will also marked as errors if they co-occur with 
#     and are less abundant than parent sequences.


# One at a time, LULU compares the selected potential "error" ASV to each matchlist
# potential "parent".

# FIRST, LULU evaluates co-occurrence with these steps:
#   1. Determine all libraries (samples) in which the potential "error" occurs
#   2. Select the same libraries (samples) for the potential "parent"
#   3. Determine how many of the libraries with the "error" also have the "parent"
#   4. If the number of libraries where the potential "parent" has a positive
#     presence is BELOW the threshold specified by the user (via the argument 
#     "minimum_relative_cooccurrence"), REJECT the potential parent.
#   5. If the co-occurrence is at or above the threshold, move to next step.

# The default setting is < minimum_relative_cooccurrence = 0.95 >, which means 95% of 
# the potential "error"'s libraries (samples) must also have the potential "parent".
# Conversely, this allows for a 1 in 20 (5%) chance that the "error" and "parent" do 
# *not* co-occur in a sample.


# IF a potential "parent" meets the co-occurrence requirement, LULU evaluates relative 
# abundance with the steps:
#   1. For the potential "parent", determine the ratio: 
#         no. reads of potential "parent" / no. reads of potential "error"
#   2. Compare this ratio to a value set by the argument "minimum_ratio".
#   3. If "parent" reads / "error" reads > minimum_ratio, then the potential "parent" 
#     ASV is accepted as a true parent, and the focal ASV/OTU is designated as an error 
#     of this parent.
#   4. If "parent" reads / "error" reads < minimum_ratio, then the potential "parent" 
#     ASV is rejected, and LULU moves to the next possible "parent" from the matchlist.

# The default setting is < minimum_ratio = 1 >, which means that potential "parents"
#   *must* have a greater number of reads than the potential "error".
# Key considerations:
#   - minimum_ratio = 1 only requires number of "parent" reads to be more than the number
#     of "error" reads.
#   - setting minimum_ratio to be a value > 1 adjusts this relative abundance, e.g.
#     minimum_ratio = 10 requires the potential "parent" to have at least 10x more 
#     reads than the potential "error".
#   - it might go without saying, but minimum_ratio should not be set to less than 1.

# A second important argument for evaluating relative abundance comparison is
#   "minimum_ratio_type" - whether a potential "error" must have fewer reads (lower
#   abundance) than the potential "parent" in EVERY sample (default setting) specified by
#   < minimum_ratio_type = min > OR if the "error" just needs to have a lower abudance
#   on average across all samples < minimum_ratio_type = avg >.


# Once LULU works through every potential "parent" for a focal ASV/OTU, it moves to the 
# next one on the list until it parses the entire file.

# When finished, LULU creates an R object containing a bunch of stuff:
#   - curated_table = a 'curated' feature table (errors removed & their read counts 
#     added to parent ASVs)
#   - curated_count = integer, the number of curated ASVs/OTUs
#   - curated_otus = a list of the 'curated' or 'valid' ASVs/OTUs
#   - discarded_count = integer, the number of error ASVs/OTUs
#   - discarded_otus = a list of the 'error' ASVs/OTUs removed by lulu
#   - runtime = self explanatory
#   - minimum_match, minimum_relative_cooccurrence = the settings you used for this run
#   - otu_map = a data frame showing which ASVs/OTUs map to which parent ASVs/OTUs
#   - original_table = your original feature table data frame
# LULU also generates and saves a .log file to your working directory, which has the
# verbose output printout for each step of the algorithm.

### END DESCRIPTION ###


# The LULU workflow requires packages lulu and dplyr.
# Install these and their dependencies before beginning.

# LULU installation
# 	Visit: https://github.com/tobiasgf/lulu for instructions
# library(devtools)
# install_github("tobiasgf/lulu")


# Set your working directory to whatever folder contains your feature table and 
# matchlist files. E.g. "your_project_table-dada2.tsv" and "your_matchlist.txt".

# setwd("~/full_path/to_directory")

# Load required packages

library(lulu)
library(dplyr)


# Read in your feature table
# NOTE: the Qiime2 conversion from .biom file to .tsv prints "# Converted from .biom 
# file" on the first line, and the header line begins with "#OTU ID".
# R could ignore the comment line by setting the read.csv argument comment.char = "#", 
# but this also strips the header since line 2 begins with "#OTU ID". 
# I have gotten around this by using argument skip = 1, which tells read.csv which lines
# to skip before starting to read in the data.

ASVtab <- read.csv("your_table-dada2.tsv",
                   skip = 1, sep = '\t', header = TRUE, as.is = TRUE, row.names = 1)



# Read in your matchlist .txt file made with blast

matchlist <- read.table("your_matchlist.txt", 
                        header=FALSE, as.is=TRUE, stringsAsFactors=FALSE)


# Run lulu
# The settings below are default settings (for more info, see description above)

your_curated <- lulu(ASVtab, matchlist,
                                minimum_match = 84,
                                minimum_relative_cooccurence = 0.95,
                                minimum_ratio_type = "min",
                                minimum_ratio = 1)


# How long did this take to run? We can check that:

print(your_curated$runtime)

# Check how many ASVs/OTUs lulu has counted as "valid"

valids <- your_curated$curated_count
print(valids)

# Check how many ASVs/OTUs lulu regarded as errors and discarded:

errors <- your_curated$discarded_count
print(errors)


# Of course, the number of valid ASVs plus error ASVs should equal the total number
# of ASVs you started with:

total <- sum(valids, errors)
print(total)


# So you can do some simple math to figure out proportion of ASVs lulu has marked as
# erroneous and/or valid:

prop_error <- errors / total
print(prop_error)

prop_valid <- valids / total
print(prop_valid)



# Now we can save versions of the lulu output for posterity or to work with in some other
# programs as needed:

# Save the entire lulu output as an R object you can return to later:

saveRDS(your_curated, file = "your_luluOutput.rds")

# If you want to re-load this output into R to work with later:

your_curated <- readRDS("your_luluOutput.rds")


# Save the lulu-curated table. I add the lulu run parameters to the file name, so I can
# easily remember how I generated that specific table.

curated_df <- your_curated$curated_table

write.table(curated_df, "your_luluCuratedTable_84_95_1.tsv",
            sep = '\t', quote = FALSE, col.names = NA)


# Save the otu map (which shows every error-parent assignment)

OTUmap <- your_curated$otu_map

write.table(OTUmap, "your_luluOTUmap_84_95_1.tsv",
            sep = '\t', quote = FALSE, col.names = NA)


# Save just a list of curated ASVs/OTUs identifiers. This could be helpful for filtering
# your data in other environments (e.g. qiime2)

curated_otus <- your_curated$curated_otus

write.table(curated_otus, "your_lulucurated_84_95_1.tsv",
            sep='\t', quote=FALSE, col.names=NA)


# Save your list of discarded ASVs/OTUs

discarded_otus <- your_curated$discarded_otus

write.table(discarded_otus, "your_luludiscarded_84_95_1.tsv",
            sep='\t', quote=FALSE, col.names=NA)


